excluded:
  - Pods
  - Carthage
  - carrefour/Entity
  - carrefour/Helpers/Assets.swift
  - carrefour/Helpers/Storyboard.swift
  - carrefour/Helpers/Strings.swift
  - ./Carthage/

line_length:
  warning: 300
  error: 300

private_outlet:
  severity: warning

mark:
  severity: error

vertical_whitespace:
  severity: error

type_name:
  max_length: 60
  excluded:
    - T

identifier_name:
  excluded:
    - id
    - y
    - x
    - u
    - d
    - i
    - c
    - p
    - to
